name: C/C++ AppImage

permissions:
  contents: write

on:
  push:
    tags:
      - "*"
jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config glib-2.0 gettext libncurses6 libgpm2 libssh2 libaspell ext2fs
      - name: configure
        run: meson Build . -Dwith-proxy=no -Dwith-bot=no -Dwith-otr=no -Dwith-capsicum=no
      - name: build
        run: DESTDIR=$PWD/AppDir ninja -C Build install
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: './*.AppImage*'
