name: C/C++ AppImage

permissions:
  contents: write

on:
  push:
    tags:
      - "*"
jobs:
  build-appimage:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: AppImageCrafters/build-appimage-action@master
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: './*.AppImage*'
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: mc-*AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
